image: node:18

build:
  stage: build
  script:
    - npm install
    - npm run build
    - zip -r artifact.zip build/
    - apt-get update && apt-get install -y maven
  artifacts:
    paths:
      - artifact.zip

deploy:
  stage: deploy
  image: maven:3-jdk-8
  script:
    - mvn deploy:deploy-file
      -DgroupId=com.example
      -DartifactId=my-artifact
      -Dversion=1.0
      -Durl=http://34.171.106.98:8081/service/rest/repository/browse/repoapp/
      -DrepositoryId=nexus-releases
      -Dfile=artifact.zip
      -Dpackaging=zip

  # Etiqueta el corredor que ejecutará la tarea
  tags:
    - runner|
