image: node:18

build:
  stage: build
  script:
    - npm install
    - npm run build
    - apt-get update && apt-get install -y zip
    - zip -r artifact.zip build/
    - apt-get update && apt-get install -y maven
  artifacts:
    paths:
      - artifact.zip
  tags:
    - runner|

deploy:
  stage: deploy
  image: maven:3-jdk-8
  script:
    - mvn deploy:deploy-file
      -DgroupId=com
      -DartifactId=app
      -Dversion=1.0
      -Durl=http://34.171.106.98:8081/repository/repoapp/
      -DrepositoryId=nexus-releases
      -Dfile=artifact.zip
      -Dpackaging=zip
      -DrepositoryUsername=conecta
      -DrepositoryPassword=Koke1988
      -DpomFile=/pom.xml
  tags:
    - runner|
