image: node:18

variables:
  VERSION: $CI_COMMIT_TAG

build:
  stage: build
  script:
    - npm install
    - npm run build
    - apt-get update && apt-get install -y zip
    - zip -r artifact.zip build/
    - apt-get update && apt-get install -y maven
  artifacts:
    paths:
      - artifact.zip
  tags:
    - runner|

deploy:
  stage: deploy
  script:
    - mvn deploy:deploy-file
      -DgroupId=com
      -DartifactId=app
      -Dversion=$VERSION
      -Durl=http://34.171.106.98:8081/repoapp/
      -DrepositoryId=nexus-releases
      -Dfile=artifact.zip
      -Dpackaging=zip
  tags:
    - runner|
