image: node:18

build:
  stage: build
  script:
    - npm install
    - npm run build
    - apt-get update && apt-get install -y zip
    - zip -r artifact.zip build/
    - apt-get update && apt-get install -y maven
  artifacts:
    paths:
      - artifact.zip
  tags:
    - runner|

deploy:
  stage: deploy
  image: maven:3-jdk-8
  script:
    - mvn deploy:deploy-file
      -DgroupId=com
      -DartifactId=app
      -Dversion=v1.21
      -Durl=http://10.128.0.18:8081/repository/repoappreact/
      -DrepositoryId=nexus-releases
      -Dfile=artifact.zip
      -Dpackaging=zip
      -DrepositoryUsername=$NEXUS_USERNAME
      -DrepositoryPassword=$NEXUS_PASSWORD
  tags:
    - runner|
