image: node:18

deploy:
  stage: deploy
  image: maven:3-jdk-8
  script:
    - mvn deploy:deploy-file
      -DgroupId=com
      -DartifactId=app
      -Dversion=v1.21
      -Durl=http://10.128.0.18:8081/repository/repoapp/
      -DrepositoryId=nexus-releases
      -Dfile=artifact.zip
      -Dpackaging=zip

  # Etiqueta el corredor que ejecutará la tarea
  tags:
    - runner|
