image: node:18

build:
  stage: build
  script:
    - npm install
    - npm run build
    - apt-get update && apt-get install -y zip
    - zip -r artifact.zip build/
    - apt-get update && apt-get install -y maven
  artifacts:
    paths:
      - artifact.zip
  tags:
    - runner|

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y git
    - TAG_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
    - VERSION=$(echo "${TAG_VERSION}" | grep -oP "v\d+\.\d+")
    - curl -v -u --upload-file ./artifact-${VERSION}.zip http://10.128.0.18:8081/repository/repoapp/com/app/${VERSION}/artifact-${VERSION}.zip
  tags:
    - runner|

