image: node:18

build:
  stage: build
  script:
    - npm install
    - npm run build
    - apt-get update && apt-get install -y zip
    - zip -r artifact.zip build/
    - apt-get update && apt-get install -y maven
  artifacts:
    paths:
      - artifact.zip
  tags:
    - runner|

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y git
    - export TAG_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
    - export NEXT_VERSION=$(semver --increment minor "${TAG_VERSION}")
    - curl -v -u conecta:Koke1988 --upload-file ./artifact.zip "http://10.128.0.18:8081/repository/repoapp/com/app/${NEXT_VERSION}/artifact.zip"
  tags:
    - runner|

